[package]
name = "eigen-operator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license-file.workspace = true
description = "eigen layer operator"

[lints]
workspace = true

[dependencies]
alloy.workspace = true
thiserror.workspace = true
futures-util.workspace = true

# eigen-rs
eigen-aggregator.workspace = true
eigen-client-avsregistry.workspace = true
eigen-crypto-bls.workspace = true
eigen-task-manager.workspace = true
eigen-types.workspace = true
rust-bls-bn254.workspace = true
reqwest.workspace = true
serde.workspace = true
tokio.workspace = true
tracing.workspace = true
rand.workspace = true
rand_core.workspace = true
eigen-logging.workspace = true
eigen-crypto-bn254.workspace = true
eigen-utils.workspace = true
url.workspace = true

hex = { version = "0.4.3", features = ["alloc"] }

# RPC Server
tarpc = { version = "0.36", features = ["full"] }

[features]
default = []
operator-testing = []
