[package]
name = "incredible-dot-product"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
alloy = { version = "1.0", features = [
    "sol-types",
    "contract",
    "full",
    "signer-aws",
    "rlp",
    "json-rpc",
    "signer-keystore",
] }
eigensdk = { workspace = true, features = ["full"] }
eyre = "0.6"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.41", features = ["test-util", "full", "sync"] }
toml = "0.8"
tracing = "0.1"
tracing-subscriber = "0.3"

[[bin]]
name = "incredible-dot-aggregator"
path = "src/bin/aggregator.rs"

[[bin]]
name = "incredible-dot-operator"
path = "src/bin/operator.rs"

[[bin]]
name = "incredible-dot-task-spammer"
path = "src/bin/task_spammer.rs"

[[bin]]
name = "incredible-dot-challenger"
path = "src/bin/challenger.rs"
