changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    # vulnerabilities
    - title: Security
      labels:
        - changelog-security
    # new features
    - title: Added
      labels:
        - changelog-added
    # changes in existing functionality
    - title: Changed
      labels:
        - changelog-changed
    # soon-to-be removed features
    - title: Deprecated
      labels:
        - changelog-deprecated
    # now removed features
    - title: Removed
      labels:
        - changelog-removed
    # documentation was added or changed
    - title: Documentation
      labels:
        - changelog-documentation

    - title: Other Changes
      labels:
        - "*"
