# syntax=docker/dockerfile:1
FROM rust:1.86-slim

# TODO : Use foundry's master instead of fork when https://github.com/foundry-rs/foundry/pull/10291 gets merged.
ARG FOUNDRY_BRANCH=matt/unlinked-workaround
ARG FOUNDRY_REPO=https://github.com/mattsse/foundry.git

# Install dependencies
RUN apt-get update && \
    apt-get install -y curl git libssl-dev pkg-config make && \
    rustup install nightly && \
    rustup default nightly

RUN git clone ${FOUNDRY_REPO} /foundry && \
    cd /foundry && \
    git checkout ${FOUNDRY_BRANCH} && \
    cargo install --locked --path ./crates/forge && \
    cargo install --locked --path ./crates/cast

WORKDIR /sdk
