[package]
name = "eigen-client-eth"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
description = "eigen layer instrumented client "
license-file.workspace = true

# docs.rs-specific configuration
# see https://docs.rs/about/metadata
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
alloy.workspace = true
async-trait.workspace = true

eigen-metrics-collectors-rpc-calls.workspace = true
hex.workspace = true
thiserror.workspace = true
tracing.workspace = true
url.workspace = true

[dev-dependencies]
# We don't use workspace due to:
# https://github.com/rust-lang/cargo/issues/4242#issuecomment-2578428685
eigen-testing-utils = { path = "../../../../tests/testing-utils" }
eigen-common = { path = "../../../common" }

once_cell.workspace = true
serial_test.workspace = true
tokio.workspace = true
