[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./" }]
solc = "0.8.27"
via-ir = true
optimizer = true
remappings = [
    "@eigenlayer/=lib/eigenlayer-middleware/lib/eigenlayer-contracts/src/",
    "@eigenlayer-scripts/=lib/eigenlayer-middleware/lib/eigenlayer-contracts/script/",
    "forge-std/=lib/forge-std/src/",
    "@m2-eigenlayer/=lib/eigenlayer-middleware-m2/lib/eigenlayer-contracts/src/",
    "@m2-eigenlayer-scripts/=lib/eigenlayer-middleware-m2/lib/eigenlayer-contracts/script/",

]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
