#![allow(unused_imports, clippy::all, rustdoc::all)]
//! This module contains the sol! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod r#awesome_vault_task_manager;
pub mod r#incredible_dot_product_task_manager;
pub mod r#incredible_squaring_task_manager;
