[package]
name = "examples-challenger"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license-file.workspace = true
authors.workspace = true
description = "challenger example"

[dependencies]
alloy.workspace = true
eigen-challenger.workspace = true
eigen-types.workspace = true
tracing.workspace = true
tokio.workspace = true

tokio-util = "0.7.11"
