[package]
name = "eigen-crypto-ecdsa"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

# docs.rs-specific configuration
# see https://docs.rs/about/metadata
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
eth-keystore = "0.5.0"
