[package]
name = "eigen-task-generator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license-file.workspace = true
description = "eigen layer task generator"

[lints]
workspace = true

[dependencies]
alloy.workspace = true
eigen-types.workspace = true
tracing.workspace = true
tokio.workspace = true

async-trait = "0.1.88"
tokio-util = "0.7.11"
