[package]
name = "eigen-task-generator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license-file.workspace = true
description = "eigen layer task generator"

[lints]
workspace = true

[dependencies]
alloy.workspace = true
eigen-types.workspace = true
thiserror.workspace = true
tracing.workspace = true
tokio.workspace = true
eigen-services-blsaggregation.workspace = true
eigen-aggregator.workspace = true
eigen-crypto-bls.workspace = true

tokio-util = "0.7.11"
