[workspace]
members = [

]

resolver = "2"

[workspace.package]
version = "0.0.1-alpha"
edition = "2021"
rust-version = "1.81"
repository = "https://github.com/Layr-Labs/eigensdk-rs"
homepage = ""
license-file = "LICENSE"


[workspace.lints]
rust.missing_debug_implementations = "warn"
rust.missing_docs = "warn"
rust.unreachable_pub = "warn"
rust.unused_must_use = "deny"
rust.rust_2018_idioms = { level = "deny", priority = -1 }
rustdoc.all = "warn"


[workspace.dependencies]
eigensdk = { path = "../../crates/eigensdk" , features = ["full"] }
