[package]
name = "eigen-services-blsaggregation"
description = "Eigen Layer SDK services blsaggregation"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license-file.workspace = true

# docs.rs-specific configuration
# see https://docs.rs/about/metadata
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
alloy.workspace = true
ark-bn254.workspace = true
ark-ec.workspace = true
eigen-client-avsregistry.workspace = true
eigen-common.workspace = true
eigen-crypto-bls.workspace = true
eigen-crypto-bn254.workspace = true
eigen-services-avsregistry.workspace = true
eigen-types.workspace = true
parking_lot.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
serde_json.workspace = true
serde.workspace = true
simple-mermaid = { version = "0.2.0", optional = true }

[dev-dependencies]
# We don't use workspace due to:
# https://github.com/rust-lang/cargo/issues/4242#issuecomment-2578428685
eigen-testing-utils = { path = "../../../tests/testing-utils" }
eigen-utils = { path = "../../utils" }
eigen-client-elcontracts = { path = "../../chainio/clients/elcontracts" }
eigen-services-operatorsinfo = { path = "../../services/operatorsinfo" }

serial_test = "3.1"
sha2 = "0.10.8"
testcontainers.workspace = true
tokio-util = "0.7.11"

# somehow required for doc-tests
simple-mermaid = "0.2.0"

[features]
docs = ["simple-mermaid"]
