[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./" }]
solc = "0.8.27"
via-ir = true
optimizer = true

remappings = [
    "@eigenlayer/=lib/eigenlayer-middleware/lib/eigenlayer-contracts/src/",
    "@eigenlayer-middleware/=lib/eigenlayer-middleware/",
    "@openzeppelin/=lib/eigenlayer-middleware/lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
    "@m2-eigenlayer/=lib/eigenlayer-middleware-m2/lib/eigenlayer-contracts/src/",
    "@m2-eigenlayer-middleware/=lib/eigenlayer-middleware-m2/",
    "@m2-openzeppelin/=lib/eigenlayer-middleware-m2/lib/openzeppelin-contracts/",
    "eigenlayer-contracts/=lib/eigenlayer-middleware/lib/eigenlayer-contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
