[package]
name = "chainio-integration-test"
description = "Integration tests for chainio clients"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license-file.workspace = true

[lib]
doctest = false

[dependencies]
tokio = { version = "1.37.0", features = ["test-util", "full", "sync"] }
alloy.workspace = true
async-trait.workspace = true
num-bigint = "0.4.4"
ark-ff.workspace = true
thiserror.workspace = true
tracing.workspace = true
eigensdk = { workspace = true, features = ["full"] }

[dev-dependencies]
futures-util.workspace = true
