[package]
name = "chainio-integration-test"
description = "Integration tests for chainio clients"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license-file.workspace = true

[dependencies]
tokio = { version = "1.37.0", features = ["test-util", "full", "sync"] }
alloy.workspace = true
async-trait.workspace = true
num-bigint = "0.4.4"
ark-ff.workspace = true
thiserror.workspace = true
tracing.workspace = true
eigen-common.workspace = true
eigen-logging.workspace = true
eigen-testing-utils.workspace = true
eigen-utils.workspace = true

[lints]
workspace = true

[dev-dependencies]
eigen-testing-utils.workspace = true
futures-util.workspace = true
