[package]
name = "examples-aggregator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license-file.workspace = true
authors.workspace = true
description = "aggregator example"

[dependencies]
alloy.workspace = true
eigen-aggregator.workspace = true
eigen-crypto-bls.workspace = true
eigen-task-processor.workspace = true
eigen-utils.workspace = true
serde.workspace = true
tokio.workspace = true
