[package]
name = "eigen-client-elcontracts"
description = "Eigen Layer core contracts sdk"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license-file.workspace = true

# docs.rs-specific configuration
# see https://docs.rs/about/metadata
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
alloy.workspace = true
eigen-crypto-bls.workspace = true
eigen-common.workspace = true
eigen-logging.workspace = true
eigen-types.workspace = true
eigen-utils.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
# We don't use workspace due to:
# https://github.com/rust-lang/cargo/issues/4242#issuecomment-2578428685
eigen-testing-utils = { path = "../../../../tests/testing-utils" }

once_cell.workspace = true
tokio.workspace = true
