//! Operator common functions.

use alloy::{
    dyn_abi::SolType,
    primitives::keccak256,
    providers::{Provider, ProviderBuilder, WsConnect},
    rpc::types::Filter,
    sol_types::SolValue,
};
use client::ClientAggregator;
use eigen_aggregator::SignedTaskResponse;
use eigen_client_avsregistry::reader::AvsRegistryChainReader;
use eigen_crypto_bls::BlsKeyPair;
use eigen_logging::logger::SharedLogger;
use eigen_task_manager::{event_decoder::decode_new_task, task_response::TaskResponse};
use eigen_task_manager::{response_calculator::ResponseCalculator, TaskManagerDefs};
use eigen_types::operator::OperatorId;
use error::OperatorError;
use futures_util::StreamExt;
use registration::register_operator;
use tracing::{error, info};

/// Tarpc Client
pub mod client;
/// Operator config
pub mod config;
/// Error
pub mod error;
/// Operator registration config
pub mod register_config;
/// Operator registration utils
pub mod registration;

/// Operator struct to handle the operator logic of processing new tasks
/// and sending signed task responses to the aggregator.
#[derive(Debug)]
pub struct Operator {
    operator_id: OperatorId,
    operator_name: String,
    client_aggregator: ClientAggregator,
    ws_rpc_url: String,
    key_pair: BlsKeyPair,
}

impl Operator {
    /// Initialize a new operator.
    /// This method does not register the operator.
    ///
    /// # Arguments
    ///
    /// * `key_pair` - The key pair of the operator.
    /// * `operator_address` - The address of the operator.
    /// * `operator_name` - The name of the operator.
    /// * `logger` - The logger.
    /// * `ws_rpc_url` - The URL of the WebSocket RPC.
    /// * `http_rpc_url` - The URL of the HTTP RPC.
    /// * `registry_coordinator_address` - The address of the registry coordinator.
    /// * `operator_state_retriever_address` - The address of the operator state retriever.
    /// * `aggregator_ip_port` - The IP and port of the aggregator.
    ///
    /// # Returns
    ///
    /// * `Result<Self, OperatorError>` - The operator.
    pub async fn new(
        logger: SharedLogger,
        config: config::OperatorConfig,
    ) -> Result<Self, OperatorError> {
        let config::OperatorConfig {
            bls_private_key,
            operator_address,
            operator_name,
            ws_rpc_url,
            http_rpc_url,
            registry_coordinator_address,
            operator_state_retriever_address,
            aggregator_ip_port,
            registration: _,
        } = config;
        let avs_registry_reader = AvsRegistryChainReader::new(
            logger.clone(),
            registry_coordinator_address,
            operator_state_retriever_address,
            http_rpc_url.to_string(),
        )
        .await?;

        let key_pair = BlsKeyPair::new(bls_private_key)?;

        // Check if the operator is registered with EigenLayer
        if !avs_registry_reader
            .is_operator_registered(operator_address)
            .await?
        {
            // Check if a registration config was provided
            let Some(registration_config) = config.registration else {
                error!(
                    "Operator {} not registered and no registration config was provided",
                    operator_name
                );
                return Err(OperatorError::RegistrationError);
            };

            register_operator(registration_config, logger, http_rpc_url, key_pair.clone()).await?;
            info!("Operator {} registered successfully", operator_name);
        }

        let client_aggregator = ClientAggregator::new(aggregator_ip_port).await?;

        let operator_id = avs_registry_reader
            .get_operator_id(operator_address)
            .await
            .map_err(|_| OperatorError::OperatorIdError)?;

        Ok(Self {
            operator_id,
            operator_name: operator_name.to_string(),
            ws_rpc_url: ws_rpc_url.to_string(),
            client_aggregator: client_aggregator.clone(),
            key_pair,
        })
    }

    /// Start listening for new task events. Operator subscribe to the event signature of the task processor.
    /// When a new task is created, the operator will process it and send the signed task response to the aggregator.
    /// User must to use the structs generated by the bindings because they implement the SolType and SolValue traits.
    ///
    /// # Arguments
    ///
    /// * `self` - The operator.
    /// * `response_calculator` - The response calculator that computes the response of a task
    ///
    /// # Returns
    ///
    /// * `Result<(), OperatorError>` - The result of the operation.
    pub async fn start<TM>(
        &self,
        response_calculator: impl ResponseCalculator<TM::Input, TM::Output>,
    ) -> Result<(), OperatorError>
    where
        TM: TaskManagerDefs,
        TM::Input:
            From<<<<TM as TaskManagerDefs>::Input as SolValue>::SolType as SolType>::RustType>,
        TM::Output: SolValue + Clone,
        TM::Output: From<<<TM::Output as SolValue>::SolType as SolType>::RustType>,
    {
        let ws = WsConnect::new(&self.ws_rpc_url);
        let provider = ProviderBuilder::new()
            .on_ws(ws)
            .await
            .map_err(|_| OperatorError::TransportError)?;

        let filter = Filter::new().event_signature(TM::NEW_TASK_EVENT_SELECTOR);
        let sub = provider
            .subscribe_logs(&filter)
            .await
            .map_err(|_| OperatorError::SubscribeLogsError)?;
        let mut stream = sub.into_stream();

        while let Some(log) = stream.next().await {
            let (task_index, task) = decode_new_task::<TM::Input>(&log)?;

            info!("{} picked up a new task", self.operator_name);

            let output = response_calculator
                .compute_response(task_index, task.input)
                .await?;
            let task_response = TaskResponse {
                task_index,
                response: output,
            };
            let signed_task_response =
                Self::sign_task_response(&self.key_pair, &self.operator_id, task_response)?;

            self.client_aggregator
                .send_signed_task_response(signed_task_response)
                .await?;
        }

        Ok(())
    }

    /// Sign the task response for the aggregator.
    ///
    /// # Arguments
    ///
    /// * `key_pair` - The key pair of the operator.
    /// * `operator_id` - The id of the operator.
    /// * `task_response` - The task response to sign.
    ///
    /// # Returns
    ///
    /// * `Result<SignedTaskResponse<Response>, OperatorError>` - The signed task response.
    fn sign_task_response<Response>(
        key_pair: &BlsKeyPair,
        operator_id: &OperatorId,
        task_response: TaskResponse<Response>,
    ) -> Result<SignedTaskResponse<Response>, OperatorError>
    where
        Response: SolValue + Clone,
        Response: From<<<Response as SolValue>::SolType as SolType>::RustType>,
    {
        let encoded = task_response.encode();
        let hash_msg = keccak256(encoded);
        let signed_msg = key_pair.sign_message(&hash_msg);
        let signed_task_response = SignedTaskResponse::new(task_response, signed_msg, *operator_id);
        info!("Operator signed task response");
        Ok(signed_task_response)
    }
}
