[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./" }]
solc = "0.8.27"
via-ir = true
optimizer = true

remappings = [
    "@eigenlayer/=../../crates/operator_sets_contracts/lib/eigenlayer-middleware/lib/eigenlayer-contracts/src/",
    "@eigenlayer-scripts/=../../crates/operator_sets_contracts/lib/eigenlayer-middleware/lib/eigenlayer-contracts/script/",
    "@eigenlayer-middleware/=../../crates/operator_sets_contracts/lib/eigenlayer-middleware/",
    "@openzeppelin/=../../crates/operator_sets_contracts/lib/eigenlayer-middleware/lib/openzeppelin-contracts/",
    "@openzeppelin-upgrades/=../../crates/operator_sets_contracts/lib/eigenlayer-middleware/lib/openzeppelin-contracts-upgradeable/",
    "forge-std/=../../crates/operator_sets_contracts/lib/forge-std/src/",
]


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
