[package]
name = "eigen-logging"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
tracing.workspace = true
tracing-subscriber.workspace = true
once_cell.workspace = true
ctor = "0.2.8"