[package]
name = "eigen-common"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
description = "Common functions for EigenLayer SDK"
license-file.workspace = true

# docs.rs-specific configuration
# see https://docs.rs/about/metadata
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
alloy.workspace = true
url.workspace = true
