[package]
name = "eigen-common"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
description = "Common functions for EigenLayer SDK"
license-file.workspace = true

[dependencies]
alloy.workspace = true
url.workspace = true
