sequenceDiagram
    participant U as Aggregator
    participant SH as ServiceHandle
    participant AR as AggregateReceiver
    participant BLS as BlsAggregatorService

    note over U: The user creates the BLS Aggregator Service
    U->>BLS: new()
    note over U: The user start the service
    U->>BLS: start()

    note over BLS: Main loop is running in the background

    note over SH: ServiceHandle is returned when the service is started
    BLS->>SH: ServiceHandle 

    note over AR: AggregateReceiver is returned when the service is started
    BLS->>AR: AggregateReceiver 

    U->>SH: initialize_task() # REVIEW

    SH->>BLS: initialize_task()

    BLS->>BLS: single_task_aggregator()
    
    U->>SH: process_signature() # REVIEW

    SH->>BLS: process_signature()

    BLS->>BLS: verify_signature()

    BLS->>BLS: check_if_stake_thresholds_met()
    note over BLS: Threshold not reached yet

    U->>SH: process_signature() # REVIEW

    SH->>BLS: process_signature()

    BLS->>BLS: verify_signature()

    BLS->>BLS: check_if_stake_thresholds_met()
    note over BLS: Threshold reached
    
    BLS->>BLS: build_aggregated_response()

    BLS->>AR: send_aggregated_response()

    AR->>U: receive_aggregated_response()
