[package]
name = "incredible-squaring"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
license-file.workspace = true

[dependencies]
alloy.workspace = true
eigen-client-avsregistry.workspace = true
eigen-crypto-bls.workspace = true
eigen-logging.workspace = true
eigen-testing-utils.workspace = true
eigen-types.workspace = true
eigen-common.workspace = true
eigen-aggregator.workspace = true
eigen-operator.workspace = true
eigen-task-manager.workspace = true
eigen-task-spammer.workspace = true
eigen-challenger.workspace = true
eigen-utils.workspace = true

tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
serde.workspace = true
tracing.workspace = true
serde_json.workspace = true
ark-ec.workspace = true

eyre = "0.6"
toml = "0.8"

[lib]
doctest = false

[[bin]]
name = "incredible-squaring-aggregator"
path = "src/bin/aggregator.rs"

[[bin]]
name = "incredible-squaring-operator"
path = "src/bin/operator.rs"

[[bin]]
name = "incredible-squaring-task-spammer"
path = "src/bin/task_spammer.rs"

[[bin]]
name = "incredible-squaring-challenger"
path = "src/bin/challenger.rs"
