[package]
name = "incredible-squaring"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
license-file.workspace = true

[dependencies]
alloy = { workspace = true, features = ["signer-keystore"] }
eigensdk = { workspace = true, features = ["full"] }
eyre.workspace = true
tokio = { workspace = true, features = ["test-util", "full", "sync"] }
tracing.workspace = true
serde.workspace = true
toml = "0.8"

[lib]
doctest = false

[[bin]]
name = "incredible-squaring-aggregator"
path = "src/bin/aggregator.rs"

[[bin]]
name = "incredible-squaring-operator"
path = "src/bin/operator.rs"

[[bin]]
name = "incredible-squaring-task-spammer"
path = "src/bin/task_spammer.rs"

[[bin]]
name = "incredible-squaring-challenger"
path = "src/bin/challenger.rs"
