[package]
name = "eigen-metrics-collectors-rpc-calls"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
eigen-logging.workspace = true
eigen-metrics-derive.workspace = true
metrics.workspace = true
