[package]
name = "eigen-metrics-collectors-rpc-calls"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
description = "eigenlayer rpc calls metrics"
license-file.workspace = true

[dependencies]
eigen-logging.workspace = true
metrics.workspace = true
