[package]
name = "examples-task-generator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license-file.workspace = true
authors.workspace = true
description = "task-generator example"

[dependencies]
alloy.workspace = true
eigen-task-generator.workspace = true
eigen-types.workspace = true
tracing.workspace = true
tokio.workspace = true

async-trait = "0.1"
