[package]
name = "eigen-telemetry"
description = "Eigen Layer telemetry"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license-file.workspace = true

[dependencies]
posthog-rs.workspace = true
