[package]
name = "eigen-client-fireblocks"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
#alloy
alloy-primitives.workspace = true
alloy-provider.workspace = true
alloy-contract.workspace = true
alloy-rpc-types.workspace = true

#misc
jsonwebtoken = "7"
hex = "0.4"
uuid = { version = "1", features = ["v4"] }
chrono = "0.4"
sha2 = "0.10"
mime = "0.3.17"
once_cell.workspace = true

#error
thiserror.workspace = true

reqwest = "0.11"
#serde
serde_json = "1.0.120"
serde.workspace = true

#eigen
eigen-utils.workspace = true

[dev-dependencies]
tokio.workspace = true

[features]
fireblock-tests = []
