[package]
name = "eigen-client-fireblocks"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
alloy-primitives.workspace = true
jsonwebtoken = "7"
hex = "0.4"
uuid = { version = "1", features = ["v4"] }
chrono = "0.4"
sha2 = "0.10"
reqwest = "0.11"
serde_json = "1.0.120"
mime = "0.3.17"
thiserror.workspace = true
eigen-utils.workspace = true
alloy-provider.workspace = true
alloy-contract.workspace = true
once_cell = "1.19.0"

[dev-dependencies]
tokio.workspace = true

[features]
fireblock-tests = []
