[package]
name = "eigen-client-fireblocks"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
description = "fireblocks support for eigenlayer"
license-file.workspace = true

[dependencies]
#alloy
alloy.workspace = true
alloy-primitives.workspace = true
chrono = "0.4"

#eigen
eigen-utils.workspace = true
hex = "0.4"
jsonwebtoken = "7"
mime = "0.3.17"
once_cell.workspace = true
reqwest = "0.11"
serde.workspace = true
serde_json = "1.0.120"
sha2 = "0.10"

#error
thiserror.workspace = true
uuid = { version = "1", features = ["v4"] }

[dev-dependencies]
tokio.workspace = true

[features]
fireblock-tests = []
