[package]
name    = "incredible-redis"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
alloy = { version = "0.13", features = [
    "sol-types",
    "contract",
    "full",
    "signer-aws",
    "rlp",
    "json-rpc",
    "signer-keystore",
] }
# Pinned to https://github.com/Layr-Labs/eigensdk-rs/pull/486 - commit: 5648654
# eigensdk = { git = "https://github.com/Layr-Labs/eigensdk-rs", rev = "5648654", features = [ "full" ] }
eigensdk = { path = "../../crates/eigensdk", features = [ "full" ] }
eyre = "0.6"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.41", features = ["test-util", "full", "sync"] }
toml = "0.8"
tracing = "0.1"
