name: Bindings

on:
  push:
    branches: [main]
  pull_request:
    branches: [ '**' ]

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Check bindings are up to date
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
            components: rustfmt, clippy

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Show Forge version
        run: forge --version
      
      - name: Generate new bindings
        run: make bindings_host

      - name: Print diff file names
        run: git diff --name-only -- crates/utils/src/

      - name: Compare existing and new bindings
        working-directory: crates/utils/src/
        run: git diff --exit-code
