name: "Pull Request Workflow"
on:
  merge_group:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

env:
  PR_NUMBER: ${{ github.event.number }}
  PR_URL: https://github.com/Layr-Labs/eigensdk-rs/pull/$PR_NUMBER

jobs:
  # Enforces the update of a changelog file on every pull request 
  # We only want this for user-visible changes, so we add a few labels
  # for which the check is skipped
  changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: dangoslen/changelog-enforcer@v3
      with:
        skipLabels: pipelines,tests,documentation

    - name: Enforce PR URL in CHANGELOG.md
    - run: grep $PR_URL CHANGELOG.md
  