name: Check anvil dump is up-to-date

on:
  push:
    branches: [main]

  pull_request:
    branches: [ '**' ]

jobs:
  check:
    name: Check anvil dump state is up to date
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # This step is needed to know if the contracts were changed.
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            contracts:
              - 'crates/contracts/lib/**'
              - 'crates/contracts/script/**'
              - 'crates/contracts/src/**'
      
      # This step runs only if some contract changed.
      # It checks the diff in the anvil state file.
      # If the diff is null, that means the anvil state has not changed,
      # i.e. the anvil state outdated and therefore this step will fail.
      # Note: if the git diff fails to fetch the changes, then the step will also fail.
      - name: Check the anvil dump has changed
        if: steps.filter.outputs.contracts == 'true'
        working-directory: crates/contracts/anvil/dump_state.json
        run: |
          if [ -z "$(git diff origin/${{ github.event.pull_request.base.ref }} -- state.json)" ]; then
            echo "The anvil dump is outdated";
            exit 1
          fi
