name: Check anvil dump up-to-date

on:
  push:
    branches: [main]

  pull_request:
    branches: [ '**' ]

jobs:
  check:
    name: Check anvil dump is up-to-date
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Check if the contracts changed
        working-directory: crates/contracts/
        id: contracts-changed
        uses: tj-actions/changed-files@v34
        with:
          files: 
            - lib/**
            - script/**
            - src/**

      # This step runs only when the contracts are changed
      - name: Check if the anvil dump is updated
        if: steps.contracts-changed.outputs.any_changed == 'true'
        working-directory: crates/contracts/anvil/contracts_deployed_anvil_state.json
        run: |
          git diff state.json
          if [ $? -eq 0 ]; then
            echo "The anvil dump is outdated";
            exit 1
          fi
          
