name: Check anvil dump is up-to-date

on:
  push:
    branches: [main]

  pull_request:
    branches: [ '**' ]
    # This makes the job run only when any of these files has been changed
    paths:
      - 'crates/contracts/lib/**'
      - 'crates/contracts/script/**'
      - 'crates/contracts/src/**'

jobs:
  check:
    name: Check anvil dump is up-to-date
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # This step checks the diff in the anvil state file.
      # If the diff is null, that means the anvil state has not changed,
      # i.e. the anvil state outdated and therefore this step will fail.
      # Note: if the git diff fails to fetch the changes, then the step will also fail.
      - name: Check the anvil dump has changed
        working-directory: crates/contracts/anvil/contracts_deployed_anvil_state.json
        run: |
          if [ -z "$(git diff origin/${{ github.event.pull_request.base.ref }} -- state.json)" ]; then
            echo "The anvil dump is outdated";
            exit 1
          fi
